[package]
authors = ["DEIP world <https://github.com/DEIPworld>"]
description = "Utility for an experiments on building custom format transactions"
edition = "2018"
homepage = "https://deip.world/"
license = "Apache-2.0"
name = "custom-transaction"
repository = "https://github.com/DEIPworld/deip-polkadot"
version = "3.0.0"

[dependencies]
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13", default-features = false }

node-template-runtime = { package = "appchain-deip-runtime", default-features = false, path = "../../runtime" }
pallet-balances = { git = "https://github.com/DEIPworld/substrate.git", branch = "polkadot-v0.9.13", default-features = false }
pallet-deip-dao = { default-features = false, path = "../../pallets/deip_dao" }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13", default-features = false }
rustc-hex = "2.1.0"
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13", default-features = false }

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "2.0.0"

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "sp-runtime/std",
    "frame-system/std",
    "node-template-runtime/std",
    "pallet-deip-dao/std",
    "sp-core/std",
    "rustc-hex/std",
    "pallet-transaction-payment/std",
    "pallet-sudo/std",
    "pallet-balances/std",
]
